services:
  postgres:
    image: postgres:15
    container_name: pg_games
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: games_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_games
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/games_db"
      JWT_SECRET: "uma_senha_bem_secreta_123"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend_games
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx_gateway
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
